<?php

namespace NS\HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

  

  public function getCategories()
  {
         
	 $categories = $this->createQueryBuilder('a')	 
          ->orderBy('a.id', 'DESC')
          ->getQuery()  
         ->getResult();	     
	 
    return $categories;    
	 
	
  }
  
   
  
  
  
}
