<?php

namespace NS\HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{

 public function getJobs($page, $nbPerPage,$id_category)
  {
    $query = $this->createQueryBuilder('a')	
      //->leftJoin('c.jobCategory', 'c')
      //->addSelect('c')      
     // ->leftJoin('a.categories', 'c')
     // ->addSelect('c')
	 ->where('a.id_category =:id_category')	
      ->setParameter('id_category', $id_category)
      ->orderBy('a.date', 'DESC')
      ->getQuery()
    ;
	
	$query      
      ->setFirstResult(($page-1) * $nbPerPage)      
      ->setMaxResults($nbPerPage)
    ;    
    return new Paginator($query, true);  
	
  }
  
  
  public function getJobsByRegion($page, $nbPerPage,$id_region)
  {
    $query = $this->createQueryBuilder('a')	
      //->leftJoin('c.jobCategory', 'c')
      //->addSelect('c')      
     // ->leftJoin('a.categories', 'c')
     // ->addSelect('c')
	 ->where('a.id_region =:id_region')	
      ->setParameter('id_region', $id_region)
      ->orderBy('a.date', 'DESC')
      ->getQuery()
    ;
	
	$query      
      ->setFirstResult(($page-1) * $nbPerPage)      
      ->setMaxResults($nbPerPage)
    ;    
    return new Paginator($query, true);  
	
  }
  
  
  
  
  
  
}
