<?php

namespace NS\HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{

  

  public function getRegions()
  {
         
	 $regions = $this->createQueryBuilder('a')	 
          ->orderBy('a.id', 'DESC')
          ->getQuery()  
         ->getResult();	     
	 
    return $regions;    
	 
	
  }
  
   
  
  
  
}
