<?php

namespace Proxies\__CG__\NS\HomeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Resume extends \NS\HomeBundle\Entity\Resume implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setResumeFirstname($resumeFirstname)
    {
        $this->__load();
        return parent::setResumeFirstname($resumeFirstname);
    }

    public function getResumeFirstname()
    {
        $this->__load();
        return parent::getResumeFirstname();
    }

    public function setResumeLastname($resumeLastname)
    {
        $this->__load();
        return parent::setResumeLastname($resumeLastname);
    }

    public function getResumeLastname()
    {
        $this->__load();
        return parent::getResumeLastname();
    }

    public function setResumeEmail($resumeEmail)
    {
        $this->__load();
        return parent::setResumeEmail($resumeEmail);
    }

    public function getResumeEmail()
    {
        $this->__load();
        return parent::getResumeEmail();
    }

    public function setIdEmployee($idEmployee)
    {
        $this->__load();
        return parent::setIdEmployee($idEmployee);
    }

    public function getIdEmployee()
    {
        $this->__load();
        return parent::getIdEmployee();
    }

    public function setResumeLogo($resumeLogo)
    {
        $this->__load();
        return parent::setResumeLogo($resumeLogo);
    }

    public function getResumeLogo()
    {
        $this->__load();
        return parent::getResumeLogo();
    }

    public function setResumePhone($resumePhone)
    {
        $this->__load();
        return parent::setResumePhone($resumePhone);
    }

    public function getResumePhone()
    {
        $this->__load();
        return parent::getResumePhone();
    }

    public function setResumeAddressOne($resumeAddressOne)
    {
        $this->__load();
        return parent::setResumeAddressOne($resumeAddressOne);
    }

    public function getResumeAddressOne()
    {
        $this->__load();
        return parent::getResumeAddressOne();
    }

    public function setResumeAddressTwo($resumeAddressTwo)
    {
        $this->__load();
        return parent::setResumeAddressTwo($resumeAddressTwo);
    }

    public function getResumeAddressTwo()
    {
        $this->__load();
        return parent::getResumeAddressTwo();
    }

    public function setResumeAlias($resumeAlias)
    {
        $this->__load();
        return parent::setResumeAlias($resumeAlias);
    }

    public function getResumeAlias()
    {
        $this->__load();
        return parent::getResumeAlias();
    }

    public function setResumeDiplomeLevel($resumeDiplomeLevel)
    {
        $this->__load();
        return parent::setResumeDiplomeLevel($resumeDiplomeLevel);
    }

    public function getResumeDiplomeLevel()
    {
        $this->__load();
        return parent::getResumeDiplomeLevel();
    }

    public function setResumeDiplome($resumeDiplome)
    {
        $this->__load();
        return parent::setResumeDiplome($resumeDiplome);
    }

    public function getResumeDiplome()
    {
        $this->__load();
        return parent::getResumeDiplome();
    }

    public function setResumeRegion($resumeRegion)
    {
        $this->__load();
        return parent::setResumeRegion($resumeRegion);
    }

    public function getResumeRegion()
    {
        $this->__load();
        return parent::getResumeRegion();
    }

    public function setResumeDiplomeUniversity($resumeDiplomeUniversity)
    {
        $this->__load();
        return parent::setResumeDiplomeUniversity($resumeDiplomeUniversity);
    }

    public function getResumeDiplomeUniversity()
    {
        $this->__load();
        return parent::getResumeDiplomeUniversity();
    }

    public function setResumeDiplomeCountry($resumeDiplomeCountry)
    {
        $this->__load();
        return parent::setResumeDiplomeCountry($resumeDiplomeCountry);
    }

    public function getResumeDiplomeCountry()
    {
        $this->__load();
        return parent::getResumeDiplomeCountry();
    }

    public function setResumeDiplomeYear($resumeDiplomeYear)
    {
        $this->__load();
        return parent::setResumeDiplomeYear($resumeDiplomeYear);
    }

    public function getResumeDiplomeYear()
    {
        $this->__load();
        return parent::getResumeDiplomeYear();
    }

    public function setResumeHobby($resumeHobby)
    {
        $this->__load();
        return parent::setResumeHobby($resumeHobby);
    }

    public function getResumeHobby()
    {
        $this->__load();
        return parent::getResumeHobby();
    }

    public function setCreatedDate($createdDate)
    {
        $this->__load();
        return parent::setCreatedDate($createdDate);
    }

    public function getCreatedDate()
    {
        $this->__load();
        return parent::getCreatedDate();
    }

    public function setUpdatedDate($updatedDate)
    {
        $this->__load();
        return parent::setUpdatedDate($updatedDate);
    }

    public function getUpdatedDate()
    {
        $this->__load();
        return parent::getUpdatedDate();
    }

    public function setResumeSkills($resumeSkills)
    {
        $this->__load();
        return parent::setResumeSkills($resumeSkills);
    }

    public function getResumeSkills()
    {
        $this->__load();
        return parent::getResumeSkills();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'resume_firstname', 'resume_lastname', 'resume_email', 'id_employee', 'resume_logo', 'resume_phone', 'resume_address_one', 'resume_address_two', 'resume_alias', 'resume_diplome_level', 'resume_diplome', 'resume_region', 'resume_diplome_university', 'resume_diplome_country', 'resume_diplome_year', 'resume_skills', 'resume_hobby', 'created_date', 'updated_date');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}